version: '2.1'
services:
 server:
  build: ./
  environment: 
    - MONGO_URI=${MONGO_URI}
    - JWT_SECRET=${JWT_SECRET}
    - BACKEND_URI=${BACKEND_URI}
    - DISQUS_SHORTNAME=${DISQUS_SHORTNAME}
  depends_on:
   database:
    condition: service_healthy
  ports:
   - "${SERVER_HOST_PORT}:${SERVER_CONTAINER_PORT}"

 database:
  image: healthcheck/mongo
  ports:
   - "${MONGO_HOST_PORT}:${MONGO_CONTAINER_PORT}"
